version: '3'

services:
  www:
    build: ./docker/apache
    depends_on:
      - mysql
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html
    ports:
      - 18080:80
  mysql:
    build: ./docker/db
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ports:
      - 13306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 14040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions